# Import

In [116]:
import numpy as np 
import math 
import scipy as sp
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from mpl_toolkits import mplot3d
%matplotlib inline
import plotly.express as px
import plotly.graph_objects as go

# Particules in a sphere centered on the box 

The particules have 3 coordinates in the sphere :
Angles Phi and Teta and radius Rad

### Number of particules 

In [117]:
n = 1000

### Uniform distribution

#### Sample 

In [118]:
data_unif = np.random.uniform(0,1,(n,3))

In [119]:
def data_to_angular(data):
    rad = np.sqrt((data[:,0]-0.5)**2+(data[:,1]-0.5)**2+(data[:,2]-0.5)**2)
    teta = np.arccos(data[:,0]/np.sqrt(data[:,0]**2 + data[:,1]**2))
    phi = np.arccos(data[:,0]/np.sqrt(data[:,0]**2 + data[:,2]**2)) 
    return(np.stack((rad, phi, teta), axis=-1))

#### Transform data to angular coordinates 

In [120]:
data_unif_angular = data_to_angular(data_unif)

### Normal distribution 

In a box

In [121]:
lower, upper = 0, 1
mu, sigma = 0.5, 0.2

x_norm = stats.truncnorm.rvs((lower-mu)/sigma,(upper-mu)/sigma,loc=mu,scale=sigma,size=n)
y_norm = stats.truncnorm.rvs((lower-mu)/sigma,(upper-mu)/sigma,loc=mu,scale=sigma,size=n)
z_norm = stats.truncnorm.rvs((lower-mu)/sigma,(upper-mu)/sigma,loc=mu,scale=sigma,size=n)

data_norm = np.stack((x_norm, y_norm, z_norm), axis=-1)

In [122]:
data_norm_angular = data_to_angular(data_norm)

### Log-normal distribution

In [123]:
sig = 0.35
s = 0.38

x_log = stats.lognorm.rvs(s, loc=0, scale=sig, size=n)
y_log = stats.lognorm.rvs(s, loc=0, scale=sig, size=n)
z_log = stats.lognorm.rvs(s, loc=0, scale=sig, size=n)

In [124]:
data_log = np.stack((x_log, y_log, z_log), axis=-1)
data_log = np.delete( data_log, np.where(data_log > 1) , axis = 0 )

In [125]:
data_log_angular = data_to_angular(data_log)

In [126]:
data_log_angular[0]

array([0.26469383, 0.7196356 , 1.04019399])

### Angular correlation

#### longueur d'arc de cercle entre 2 points

In [127]:
r = 0.5
def arc_length(point_1, point_2, radius):
    delta_sig = np.arccos(np.sin(point_1[1])*np.sin(point_2[1])+np.cos(point_1[1])*np.cos(point_2[1])*np.cos(abs(point_1[2]-point_2[2])))
    return(delta_sig*r)


In [128]:
math.floor(np.pi/(0.02*2))

78

In [129]:
point_1 = data_log_angular[0]

In [130]:
point_2 = data_log_angular[1]

In [131]:
np.arccos(np.sin(point_1[1])*np.sin(point_2[1])+np.cos(point_1[1])*np.cos(point_2[1])*np.cos(abs(point_1[2]-point_2[2])))

0.2431478510948091

In [132]:
d = 0.05
np.arange(math.floor((np.pi*r)/(2*d))+1)*d*2*np.pi

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265, 3.45575192, 3.76991118, 4.08407045, 4.39822972,
       4.71238898])

In [138]:
#Max arc length is Pi 
#Same as for the box but using arc length between points 

def angular_pair_correlation(data, r, d):
    bins = np.zeros(math.floor((np.pi*r)/(2*d))+1)
    for i in range(len(data)):
        for j in range(i+1, len(data)):
            l = arc_length(data[i],data[j], r)
            bins[math.floor(l/d)] += 1
    #we need to normalize  divide each bins by the perimeter of the circle of radius r 
    p = (np.arange(math.floor((np.pi*r)/(2*d))+1)+1)*d*2*np.pi
    return(np.divide(bins, p))


 

In [140]:
res = angular_pair_correlation(data_unif_angular, 0.5, 0.01)

In [141]:
res

array([1.58200013e+04, 1.88519030e+04, 1.82603771e+04, 1.73478888e+04,
       1.67462831e+04, 1.63637807e+04, 1.54152931e+04, 1.47954414e+04,
       1.40480763e+04, 1.34867899e+04, 1.30753020e+04, 1.27854471e+04,
       1.20333380e+04, 1.15762485e+04, 1.12830244e+04, 1.09627914e+04,
       1.08244085e+04, 1.00506347e+04, 9.89273620e+03, 9.29066980e+03,
       9.21582909e+03, 8.77016080e+03, 8.37155001e+03, 8.09966031e+03,
       7.70373587e+03, 7.29664201e+03, 6.94622907e+03, 6.66745529e+03,
       6.40680967e+03, 5.94019299e+03, 5.87230400e+03, 5.38142651e+03,
       5.13781094e+03, 4.86780074e+03, 4.61367444e+03, 4.35686657e+03,
       4.16254698e+03, 3.86076386e+03, 3.55935747e+03, 3.32474676e+03,
       3.09032318e+03, 2.91973533e+03, 2.62864746e+03, 2.42421916e+03,
       2.25504870e+03, 2.08908162e+03, 1.99045267e+03, 1.78585109e+03,
       1.61818352e+03, 1.52947900e+03, 1.42490484e+03, 1.30354020e+03,
       1.21858634e+03, 1.11821084e+03, 1.07472992e+03, 9.69139921e+02,
      